version: 2
databaseImage: false

services:
  - type: web
    name: deerflow
    env: python
  startCommand: |
  # Запуск Ollama в фоне
  ollama serve &

  # Ожидание запуска сервера Ollama
  sleep 10

  # Загрузка модели Llama3
  ollama pull llama3

  # Запуск Streamlit
  streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    plan: free
